### ISSUE TITLE
Installing pyinterval on Windows with Python 3.6

### ISSUE THREAD

**Issue by ifisl** [taschini/pyinterval#17]
Hi,

This might not be the right place for this question since it concerns `pycrlibm`. I asked the same question at https://github.com/taschini/pycrlibm/issues but there is more activity in this project so I am asking the same question here as well.

I tried installing `pyinterval` on Windows and Python 3.6. The complete output of the error I am getting is below.
```
(oe-3.6.2) C:\Users\ifisl\workspace>pip install pyinterval
Collecting pyinterval
  Using cached pyinterval-1.2.0.tar.gz
Collecting crlibm==1.*,>=1.0.3 (from pyinterval)
  Using cached crlibm-1.0.3.tar.gz
Requirement already satisfied: six>=1.10 in c:\users\ifisl\workspace\venvs\oe-3.
6.2\lib\site-packages (from pyinterval)
Installing collected packages: crlibm, pyinterval
  Running setup.py install for crlibm ... error
    Complete output from command c:\users\ifisl\workspace\venvs\oe-3.6.2\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ifisl\\AppData\\Local\\Temp\\pip-build-24w2c8s7\\crlibm\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ifisl\AppData\Local\Temp\pip-qajjsl7u-record\install-record.txt --single-version-externally-managed --compile --install-headers c:\users\ifisl\workspace\venvs\oe-3.6.2\include\site\python3.6\crlibm:
    running install
    running build
    running build_ext
    using msys2 compiler
    building 'crlibm' extension
    creating build
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\ext
    C:\msys64\mingw64\bin\gcc.exe -mdll -O2 -Wall -fno-strict-aliasing -fwrapv -DMS_WIN64 -Ibuild/crlibm/include -Ic:\users\ifisl\workspace\venvs\oe-3.6.2\include "-IC:\Program Files\Python362\include" "-IC:\Program Files\Python362\include" -c ext/crlibmmodule.c -o build\temp.win-amd64-3.6\Release\ext\crlibmmodule.o
    ext/crlibmmodule.c:7:10: fatal error: crlibm.h: No such file or directory
     #include "crlibm.h"
              ^~~~~~~~~~
    compilation terminated.
    invoking: ['make', 'msys2', 'PYTHON_DLL=c:\\users\\ifisl\\workspace\\venvs\\oe-3.6.2\\scripts\\python36.dll']
    error: [WinError 2] The system cannot find the file specified

    ----------------------------------------
```

I followed all instructions in http://stackoverflow.com/a/30071634 on installing/configuring MinGW-w64 under MSYS2 and am getting the error above. I tried to look for `crlibm.h` at http://lipforge.ens-lyon.fr/www/crlibm but that page does not exist any more.

Is there anything I can do to install `pyinterval` without `pycrlibm`? If not, how can I install `pycrlibm` on Windows with Python 3.6?

Thanks!
Igor

**Comment by jmmcd** [comment]
I also have a problem on Windows 10 with Python 3.7.3. Not sure if the same issue. I haven't done anything to install MINGW, I just installed gitbash.

```
james@nu MINGW64 ~
$ pip install pyinterval
Collecting pyinterval
  Using cached pyinterval-1.2.0-py3-none-any.whl
Collecting crlibm==1.*,>=1.0.3
  Using cached crlibm-1.0.3.tar.gz (1.6 MB)
Requirement already satisfied: six>=1.10 in c:\users\james\appdata\local\continuum\anaconda3\lib\site-packages (from pyinterval) (1.16.0)
Building wheels for collected packages: crlibm
  Building wheel for crlibm (setup.py): started
  Building wheel for crlibm (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\james\AppData\Local\Continuum\anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\james\\AppData\\Local\\Temp\\pip-install-tn1214d_\\crlibm_dff66045c18042658aac977be79f553b\\setup.py'"'"'; __file__='"'"'C:\\Users\\james\\AppData\\Local\\Temp\\pip-install-tn1214d_\\crlibm_dff66045c18042658aac977be79f553b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\james\AppData\Local\Temp\pip-wheel-916vfr4x'
       cwd: C:\Users\james\AppData\Local\Temp\pip-install-tn1214d_\crlibm_dff66045c18042658aac977be79f553b\
  Complete output (36 lines):
  running bdist_wheel
  running build
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\james\AppData\Local\Temp\pip-install-tn1214d_\crlibm_dff66045c18042658aac977be79f553b\setup.py", line 189, in <module>
      setup(**metadata)
    File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\distutils\command\build_ext.py", line 309, in run
      force=self.force)
    File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\distutils\ccompiler.py", line 1031, in new_compiler
      return klass(None, dry_run, force)
    File "C:\Users\james\AppData\Local\Temp\pip-install-tn1214d_\crlibm_dff66045c18042658aac977be79f553b\setup.py", line 58, in __init__
      cygwinccompiler.CygwinCCompiler.__init__(self, verbose, dry_run, force)
    File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\distutils\cygwinccompiler.py", line 129, in __init__
      if self.ld_version >= "2.10.90":
  TypeError: '>=' not supported between instances of 'NoneType' and 'str'
  ----------------------------------------
  ERROR: Failed building wheel for crlibm
  Running setup.py clean for crlibm
Failed to build crlibm
Installing collected packages: crlibm, pyinterval
    Running setup.py install for crlibm: started
    Running setup.py install for crlibm: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\james\AppData\Local\Continuum\anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\james\\AppData\\Local\\Temp\\pip-install-tn1214d_\\crlibm_dff66045c18042658aac977be79f553b\\setup.py'"'"'; __file__='"'"'C:\\Users\\james\\AppData\\Local\\Temp\\pip-install-tn1214d_\\crlibm_dff66045c18042658aac977be79f553b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\james\AppData\Local\Temp\pip-record-xrsirykh\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\james\AppData\Local\Continuum\anaconda3\Include\crlibm'
         cwd: C:\Users\james\AppData\Local\Temp\pip-install-tn1214d_\crlibm_dff66045c18042658aac977be79f553b\
    Complete output (38 lines):
    running install
    running build
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\james\AppData\Local\Temp\pip-install-tn1214d_\crlibm_dff66045c18042658aac977be79f553b\setup.py", line 189, in <module>
        setup(**metadata)
      File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\distutils\command\build_ext.py", line 309, in run
        force=self.force)
      File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\distutils\ccompiler.py", line 1031, in new_compiler
        return klass(None, dry_run, force)
      File "C:\Users\james\AppData\Local\Temp\pip-install-tn1214d_\crlibm_dff66045c18042658aac977be79f553b\setup.py", line 58, in __init__
        cygwinccompiler.CygwinCCompiler.__init__(self, verbose, dry_run, force)
      File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\distutils\cygwinccompiler.py", line 129, in __init__
        if self.ld_version >= "2.10.90":
    TypeError: '>=' not supported between instances of 'NoneType' and 'str'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\james\AppData\Local\Continuum\anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\james\\AppData\\Local\\Temp\\pip-install-tn1214d_\\crlibm_dff66045c18042658aac977be79f553b\\setup.py'"'"'; __file__='"'"'C:\\Users\\james\\AppData\\Local\\Temp\\pip-install-tn1214d_\\crlibm_dff66045c18042658aac977be79f553b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\james\AppData\Local\Temp\pip-record-xrsirykh\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\james\AppData\Local\Continuum\anaconda3\Include\crlibm' Check the logs for full command output.
```

**Comment by SofiiaRomah** [comment]
@jmmcd @ifisl have you fixed this issue?
