### ISSUE TITLE
Invalid interval component due to precision?

### ISSUE THREAD

**Issue by b1rd1e** [taschini/pyinterval#18]
Hi,

Could you tell why the following error is being thrown? Are the operators used not able to handle this much precision? 

**Error1:**
Traceback (most recent call last):
  File "c.py", line 78, in <module>
    input_prev[index] = interval(lower,upper)
  File "path/python2.7/site-packages/interval/__init__.py", line 101, in __new__
    return cls.union(process(x) for x in args)
  File "path/python2.7/site-packages/interval/__init__.py", line 185, in union
    return cls._canonical(c for i in intervals for c in i)
  File "path/python2.7/site-packages/interval/__init__.py", line 162, in _canonical
    components = [c for c in components if c.inf <= c.sup]
  File "path/python2.7/site-packages/interval/__init__.py", line 185, in <genexpr>
    return cls._canonical(c for i in intervals for c in i)
  File "path/python2.7/site-packages/interval/__init__.py", line 101, in <genexpr>
    return cls.union(process(x) for x in args)
  File "path/python2.7/site-packages/interval/__init__.py", line 100, in process
    raise **cls.ComponentError("Invalid interval component:** " + repr(x))
interval.ComponentError: Invalid interval component: interval([0.020530565167243362, 0.020530565167243373])

**Similarly,**
 File "/path/python2.7/site-packages/interval/__init__.py", line 100, in process
    raise **cls.ComponentError("Invalid interval component:** " + repr(x))
interval.ComponentError: Invalid interval component: interval([0.004029219530949634, 0.004029219530949636])

**Comment by taschini** [comment]
I cannot reproduce it. Both intervals seem to be perfectly fine:

```
>>> from interval import interval
>>> interval([0.020530565167243362, 0.020530565167243373])
>>> interval([0.004029219530949634, 0.004029219530949636])
```

I need more context to be able to diagnose what is wrong.

**Comment by b1rd1e** [comment]
Ok, thanks!
