### ISSUE TITLE
Installation with pip fails " ValueError: Unknown MS Compiler version 1916"

### ISSUE THREAD

**Issue by Askill** [taschini/pyinterval#26]
Error:

`C:\WINDOWS\system32>pip install pyinterval
Collecting pyinterval
  Using cached pyinterval-1.2.0-py3-none-any.whl
Requirement already satisfied: six>=1.10 in c:\users\ofjok\appdata\local\programs\python\python37\lib\site-packages (from pyinterval) (1.14.0)
Collecting crlibm==1.*,>=1.0.3
  Using cached crlibm-1.0.3.tar.gz (1.6 MB)
Building wheels for collected packages: crlibm
  Building wheel for crlibm (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\ofjok\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ofjok\\AppData\\Local\\Temp\\pip-install-fm33ar7k\\crlibm_fd5461c661ab45d2b35ddbcdb8691d42\\setup.py'"'"'; __file__='"'"'C:\\Users\\ofjok\\AppData\\Local\\Temp\\pip-install-fm33ar7k\\crlibm_fd5461c661ab45d2b35ddbcdb8691d42\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\ofjok\AppData\Local\Temp\pip-wheel-jyi72ead'
       cwd: C:\Users\ofjok\AppData\Local\Temp\pip-install-fm33ar7k\crlibm_fd5461c661ab45d2b35ddbcdb8691d42\
  Complete output (40 lines):
  running bdist_wheel
  running build
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\ofjok\AppData\Local\Temp\pip-install-fm33ar7k\crlibm_fd5461c661ab45d2b35ddbcdb8691d42\setup.py", line 189, in <module>
      setup(**metadata)
    File "c:\users\ofjok\appdata\local\programs\python\python37\lib\site-packages\setuptools\__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "c:\users\ofjok\appdata\local\programs\python\python37\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\ofjok\appdata\local\programs\python\python37\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\users\ofjok\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\ofjok\appdata\local\programs\python\python37\lib\site-packages\wheel\bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "c:\users\ofjok\appdata\local\programs\python\python37\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\ofjok\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\ofjok\appdata\local\programs\python\python37\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\ofjok\appdata\local\programs\python\python37\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\ofjok\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\ofjok\appdata\local\programs\python\python37\lib\distutils\command\build_ext.py", line 309, in run
      force=self.force)
    File "c:\users\ofjok\appdata\local\programs\python\python37\lib\distutils\ccompiler.py", line 1031, in new_compiler
      return klass(None, dry_run, force)
    File "C:\Users\ofjok\AppData\Local\Temp\pip-install-fm33ar7k\crlibm_fd5461c661ab45d2b35ddbcdb8691d42\setup.py", line 58, in __init__
      cygwinccompiler.CygwinCCompiler.__init__(self, verbose, dry_run, force)
    File "c:\users\ofjok\appdata\local\programs\python\python37\lib\distutils\cygwinccompiler.py", line 157, in __init__
      self.dll_libraries = get_msvcr()
    File "C:\Users\ofjok\AppData\Local\Temp\pip-install-fm33ar7k\crlibm_fd5461c661ab45d2b35ddbcdb8691d42\setup.py", line 25, in get_msvcr
      return _get_msvcr()
    File "c:\users\ofjok\appdata\local\programs\python\python37\lib\distutils\cygwinccompiler.py", line 86, in get_msvcr
      raise ValueError("Unknown MS Compiler version %s " % msc_ver)
  ValueError: Unknown MS Compiler version 1916
  ----------------------------------------
  ERROR: Failed building wheel for crlibm
  Running setup.py clean for crlibm
Failed to build crlibm
Installing collected packages: crlibm, pyinterval
    Running setup.py install for crlibm ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\ofjok\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ofjok\\AppData\\Local\\Temp\\pip-install-fm33ar7k\\crlibm_fd5461c661ab45d2b35ddbcdb8691d42\\setup.py'"'"'; __file__='"'"'C:\\Users\\ofjok\\AppData\\Local\\Temp\\pip-install-fm33ar7k\\crlibm_fd5461c661ab45d2b35ddbcdb8691d42\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ofjok\AppData\Local\Temp\pip-record-obaqt1et\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\ofjok\appdata\local\programs\python\python37\Include\crlibm'
         cwd: C:\Users\ofjok\AppData\Local\Temp\pip-install-fm33ar7k\crlibm_fd5461c661ab45d2b35ddbcdb8691d42\
    Complete output (42 lines):
    running install
    running build
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ofjok\AppData\Local\Temp\pip-install-fm33ar7k\crlibm_fd5461c661ab45d2b35ddbcdb8691d42\setup.py", line 189, in <module>
        setup(**metadata)
      File "c:\users\ofjok\appdata\local\programs\python\python37\lib\site-packages\setuptools\__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\ofjok\appdata\local\programs\python\python37\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\ofjok\appdata\local\programs\python\python37\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\ofjok\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\ofjok\appdata\local\programs\python\python37\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\ofjok\appdata\local\programs\python\python37\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\ofjok\appdata\local\programs\python\python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\ofjok\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\ofjok\appdata\local\programs\python\python37\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\ofjok\appdata\local\programs\python\python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\ofjok\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\ofjok\appdata\local\programs\python\python37\lib\distutils\command\build_ext.py", line 309, in run
        force=self.force)
      File "c:\users\ofjok\appdata\local\programs\python\python37\lib\distutils\ccompiler.py", line 1031, in new_compiler
        return klass(None, dry_run, force)
      File "C:\Users\ofjok\AppData\Local\Temp\pip-install-fm33ar7k\crlibm_fd5461c661ab45d2b35ddbcdb8691d42\setup.py", line 58, in __init__
        cygwinccompiler.CygwinCCompiler.__init__(self, verbose, dry_run, force)
      File "c:\users\ofjok\appdata\local\programs\python\python37\lib\distutils\cygwinccompiler.py", line 157, in __init__
        self.dll_libraries = get_msvcr()
      File "C:\Users\ofjok\AppData\Local\Temp\pip-install-fm33ar7k\crlibm_fd5461c661ab45d2b35ddbcdb8691d42\setup.py", line 25, in get_msvcr
        return _get_msvcr()
      File "c:\users\ofjok\appdata\local\programs\python\python37\lib\distutils\cygwinccompiler.py", line 86, in get_msvcr
        raise ValueError("Unknown MS Compiler version %s " % msc_ver)
    ValueError: Unknown MS Compiler version 1916

ERROR: Command errored out with exit status 1: 'c:\users\ofjok\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ofjok\\AppData\\Local\\Temp\\pip-install-fm33ar7k\\crlibm_fd5461c661ab45d2b35ddbcdb8691d42\\setup.py'"'"'; __file__='"'"'C:\\Users\\ofjok\\AppData\\Local\\Temp\\pip-install-fm33ar7k\\crlibm_fd5461c661ab45d2b35ddbcdb8691d42\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ofjok\AppData\Local\Temp\pip-record-obaqt1et\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\ofjok\appdata\local\programs\python\python37\Include\crlibm' Check the logs for full command output.`

**Comment by kimbar** [comment]
Since parts of this library are written in C you need to install an appropriate compiler. This is not specific to this library, but to all compiled ones. Most commonly this occurs with `numpy` or `matplotlib` when not under Anaconda (or similar). Please refer to https://stackoverflow.com/a/28414059/12510519

HTH

**Comment by Askill** [comment]
Thank you!
